'use strict';

/**
* Create a two column table listing emoticons.
*
* @return {String} emotes table
*/
const emotes = {
	':4head:': 'http://cbc.pokecommunity.com:8000/assets/4head.png',
	':absol:': 'http://cbc.pokecommunity.com:8000/assets/absol.png',
	':aggron:': 'http://cbc.pokecommunity.com:8000/assets/aggron.png',
	':aids:': 'http://cbc.pokecommunity.com:8000/assets/aids.png',
	':alarm:': 'http://cbc.pokecommunity.com:8000/assets/alarm.gif',
	':ampharos:': 'http://cbc.pokecommunity.com:8000/assets/ampharos.png',
	':ana:': 'http://cbc.pokecommunity.com:8000/assets/ana.png',
	':arcanine:': 'http://cbc.pokecommunity.com:8000/assets/arcanine.png',
	':arceus:': 'http://cbc.pokecommunity.com:8000/assets/arceus.png',
	':armycat:': 'http://cbc.pokecommunity.com:8000/assets/armycat.png',
	':ashhug:': 'http://cbc.pokecommunity.com:8000/assets/ashhug.png',
	':ball:': 'http://cbc.pokecommunity.com:8000/assets/ball.gif',
	':barrel:': 'http://cbc.pokecommunity.com:8000/assets/barrel.gif',
	':bastion:': 'http://cbc.pokecommunity.com:8000/assets/bastion.png',
	':bearhug:': 'http://cbc.pokecommunity.com:8000/assets/bearhug.png',
	':bed:': 'http://cbc.pokecommunity.com:8000/assets/bed.gif',
	':bellossom:': 'http://cbc.pokecommunity.com:8000/assets/bellossom.png',
	':bidoof:': 'http://cbc.pokecommunity.com:8000/assets/bidoof.png',
	':blastoise:': 'http://cbc.pokecommunity.com:8000/assets/blastoise.png',
	':blink:': 'http://cbc.pokecommunity.com:8000/assets/blink.gif',
	':blissey:': 'http://cbc.pokecommunity.com:8000/assets/blissey.png',
	':blush:': 'http://cbc.pokecommunity.com:8000/assets/blush.png',
	':blust:': 'http://cbc.pokecommunity.com:8000/assets/blust.gif',
	':boatydrugs:': 'http://cbc.pokecommunity.com:8000/assets/boatydrugs.png',
	':bowie:': 'http://cbc.pokecommunity.com:8000/assets/bowie.png',
	':bulbasaur:': 'http://cbc.pokecommunity.com:8000/assets/bulbasaur.png',
	':bunny:': 'http://cbc.pokecommunity.com:8000/assets/bunny.gif',
	':camiss:': 'http://cbc.pokecommunity.com:8000/assets/camiss.png',
	':carol:': 'http://cbc.pokecommunity.com:8000/assets/carol.png',
	':castform:': 'http://cbc.pokecommunity.com:8000/assets/castform.png',
	':catflip:': 'http://cbc.pokecommunity.com:8000/assets/catflip.png',
	':censor:': 'http://cbc.pokecommunity.com:8000/assets/censor.png',
	':chansey:': 'http://cbc.pokecommunity.com:8000/assets/chansey.png',
	':charizard:': 'http://cbc.pokecommunity.com:8000/assets/charizard.png',
	':charmander:': 'http://cbc.pokecommunity.com:8000/assets/charmander.png',
	':cheers:': 'http://cbc.pokecommunity.com:8000/assets/cheers.png',
	':chikorita:': 'http://cbc.pokecommunity.com:8000/assets/chikorita.png',
	':choicehug:': 'http://cbc.pokecommunity.com:8000/assets/choicehug.png',
	':choke:': 'http://cbc.pokecommunity.com:8000/assets/choke.png',
	':christos:': 'http://cbc.pokecommunity.com:8000/assets/christos.png',
	':clefairy:': 'http://cbc.pokecommunity.com:8000/assets/clefairy.png',
	':clown:': 'http://cbc.pokecommunity.com:8000/assets/clown.png',
	':cookie:': 'http://cbc.pokecommunity.com:8000/assets/cookie.png',
	':cthulhu:': 'http://cbc.pokecommunity.com:8000/assets/cthulhu.png',
	':curry:': 'http://cbc.pokecommunity.com:8000/assets/curry.png',
	':dab:': 'http://cbc.pokecommunity.com:8000/assets/dab.png',
	':dance:': 'http://cbc.pokecommunity.com:8000/assets/dance.gif',
	':dedenne:': 'http://cbc.pokecommunity.com:8000/assets/dedenne.png',
	':delivert:': 'http://cbc.pokecommunity.com:8000/assets/delivert.png',
	':diddy:': 'http://cbc.pokecommunity.com:8000/assets/diddy.png',
	':dinner:': 'http://cbc.pokecommunity.com:8000/assets/dinner.png',
	':ditto:': 'http://cbc.pokecommunity.com:8000/assets/ditto.png',
	':dk:': 'http://cbc.pokecommunity.com:8000/assets/dk.png',
	':doomfist:': 'http://cbc.pokecommunity.com:8000/assets/doomfist.png',
	':drama:': 'http://cbc.pokecommunity.com:8000/assets/drama.png',
	':drowzee:': 'http://cbc.pokecommunity.com:8000/assets/drowzee.png',
	':dva:': 'http://cbc.pokecommunity.com:8000/assets/dva.png',
	':eevee:': 'http://cbc.pokecommunity.com:8000/assets/eevee.png',
	':electrode:': 'http://cbc.pokecommunity.com:8000/assets/electrode.png',
	':emboar:': 'http://cbc.pokecommunity.com:8000/assets/emboar.png',
	':espurr:': 'http://cbc.pokecommunity.com:8000/assets/espurr.png',
	':eyes:': 'http://cbc.pokecommunity.com:8000/assets/eyes.png',
	':fatbowie:': 'http://cbc.pokecommunity.com:8000/assets/bowie.png',
	':feebas:': 'http://cbc.pokecommunity.com:8000/assets/feebas.png',
	':fish:': 'http://cbc.pokecommunity.com:8000/assets/fish.gif',
	':flirt:': 'http://cbc.pokecommunity.com:8000/assets/flirt.png',
	':flygon:': 'http://cbc.pokecommunity.com:8000/assets/flygon.png',
	':frank:': 'http://cbc.pokecommunity.com:8000/assets/frank.png',
	':gav:': 'http://cbc.pokecommunity.com:8000/assets/gav.png',
	':gawk:': 'http://cbc.pokecommunity.com:8000/assets/gawk.png',
	':genji:': 'http://cbc.pokecommunity.com:8000/assets/genji.png',
	':glare:': 'http://cbc.pokecommunity.com:8000/assets/glare.png',
	':gloom:': 'http://cbc.pokecommunity.com:8000/assets/gloom.png',
	':goodra:': 'http://cbc.pokecommunity.com:8000/assets/goodra.png',
	':goomy:': 'http://cbc.pokecommunity.com:8000/assets/goomy.png',
	':growlithe:': 'http://cbc.pokecommunity.com:8000/assets/growlithe.png',
	':hamster:': 'http://cbc.pokecommunity.com:8000/assets/hamster.png',
	':hamtaro:': 'http://cbc.pokecommunity.com:8000/assets/hamtaro.gif',
	':hanzo:': 'http://cbc.pokecommunity.com:8000/assets/hanzo.png',
	':harambe:': 'http://cbc.pokecommunity.com:8000/assets/harambe.png',
	':helix:': 'http://cbc.pokecommunity.com:8000/assets/helix.png',
	':houndoom:': 'http://cbc.pokecommunity.com:8000/assets/houndoom.png',
	':hug:': 'http://cbc.pokecommunity.com:8000/assets/hug.png',
	':hypno:': 'http://cbc.pokecommunity.com:8000/assets/hypno.png',
	':infernape:': 'http://cbc.pokecommunity.com:8000/assets/infernape.png',
	':jack:': 'http://cbc.pokecommunity.com:8000/assets/jack.png',
	':jigglypuff:': 'http://cbc.pokecommunity.com:8000/assets/jigglypuff.png',
	':joanne:': 'http://cbc.pokecommunity.com:8000/assets/joanne.png',
	':junkrat:': 'http://cbc.pokecommunity.com:8000/assets/junkrat.png',
	':jynx:': 'http://cbc.pokecommunity.com:8000/assets/jynx.png',
	':kanye:': 'http://cbc.pokecommunity.com:8000/assets/kanye.png',
	':kappa:': 'http://cbc.pokecommunity.com:8000/assets/kappa.png',
	':kappapride:': 'http://cbc.pokecommunity.com:8000/assets/kappapride.png',
	':kappaross:': 'http://cbc.pokecommunity.com:8000/assets/kappaross.png',
	':keepo:': 'http://cbc.pokecommunity.com:8000/assets/keepo.png',
	':kermit:': 'http://cbc.pokecommunity.com:8000/assets/kermit.png',
	':khaled:': 'http://cbc.pokecommunity.com:8000/assets/khaled.png',
	':kitty:': 'http://cbc.pokecommunity.com:8000/assets/kitty.png',
	':kreygasm:': 'http://cbc.pokecommunity.com:8000/assets/kreygasm.png',
	':lapras:': 'http://cbc.pokecommunity.com:8000/assets/lapras.png',
	':latias:': 'http://cbc.pokecommunity.com:8000/assets/latias.png',
	':latios:': 'http://cbc.pokecommunity.com:8000/assets/latios.png',
	':ledian:': 'http://cbc.pokecommunity.com:8000/assets/ledian.png',
	':leg:': 'http://cbc.pokecommunity.com:8000/assets/leg.png',
	':lewd:': 'http://cbc.pokecommunity.com:8000/assets/lewd.png',
	':lickilicky:': 'http://cbc.pokecommunity.com:8000/assets/lickilicky.png',
	':lickitung:': 'http://cbc.pokecommunity.com:8000/assets/lickitung.gif',
	':lileep:': 'http://cbc.pokecommunity.com:8000/assets/lileep.png',
	':link:': 'http://cbc.pokecommunity.com:8000/assets/link.png',
	':loudred:': 'http://cbc.pokecommunity.com:8000/assets/loudred.png',
	':lucio:': 'http://cbc.pokecommunity.com:8000/assets/lucio.png',
	':ludicolo:': 'http://cbc.pokecommunity.com:8000/assets/ludicolo.png',
	':luvdisc:': 'http://cbc.pokecommunity.com:8000/assets/luvdisc.png',
	':lyin:': 'http://cbc.pokecommunity.com:8000/assets/lyin.png',
	':magikarp:': 'http://cbc.pokecommunity.com:8000/assets/magikarp.png',
	':mccree:': 'http://cbc.pokecommunity.com:8000/assets/mccree.png',
	':meganium:': 'http://cbc.pokecommunity.com:8000/assets/meganium.png',
	':mei:': 'http://cbc.pokecommunity.com:8000/assets/mei.png',
	':meowstic:': 'http://cbc.pokecommunity.com:8000/assets/meowstic.png',
	':meowsticf:': 'http://cbc.pokecommunity.com:8000/assets/meowsticf.png',
	':meowth:': 'http://cbc.pokecommunity.com:8000/assets/meowth.png',
	':mercy:': 'http://cbc.pokecommunity.com:8000/assets/mercy.png',
	':mermaid:': 'http://cbc.pokecommunity.com:8000/assets/mermaid.png',
	':metagross:': 'http://cbc.pokecommunity.com:8000/assets/metagross.png',
	':mind:': 'http://cbc.pokecommunity.com:8000/assets/mind.png',
	':moo:': 'http://cbc.pokecommunity.com:8000/assets/moo.gif',
	':mrmime:': 'http://cbc.pokecommunity.com:8000/assets/mrmime.png',
	':mudkip:': 'http://cbc.pokecommunity.com:8000/assets/mudkip.png',
	':muk:': 'http://cbc.pokecommunity.com:8000/assets/muk.png',
	':no:': 'http://cbc.pokecommunity.com:8000/assets/no.png',
	':nw:': 'http://cbc.pokecommunity.com:8000/assets/nw.gif',
	':oddish:': 'http://cbc.pokecommunity.com:8000/assets/oddish.png',
	':ok:': 'http://cbc.pokecommunity.com:8000/assets/ok.png',
	':orisa:': 'http://cbc.pokecommunity.com:8000/assets/orisa.png',
	':pachirisu:': 'http://cbc.pokecommunity.com:8000/assets/pachirisu.png',
	':pancham:': 'http://cbc.pokecommunity.com:8000/assets/pancham.png',
	':pangoro:': 'http://cbc.pokecommunity.com:8000/assets/pangoro.png',
	':papabless:': 'http://cbc.pokecommunity.com:8000/assets/papabless.png',
	':papi:': 'http://cbc.pokecommunity.com:8000/assets/papi.png',
	':pear:': 'http://cbc.pokecommunity.com:8000/assets/pear.png',
	':petty:': 'http://cbc.pokecommunity.com:8000/assets/petty.png',
	':pharah:': 'http://cbc.pokecommunity.com:8000/assets/pharah.png',
	':pikachu:': 'http://cbc.pokecommunity.com:8000/assets/pikachu.png',
	':pikahug:': 'http://cbc.pokecommunity.com:8000/assets/pikahug.png',
	':pix:': 'http://cbc.pokecommunity.com:8000/assets/pix.png',
	':pjsalt:': 'http://cbc.pokecommunity.com:8000/assets/pjsalt.png',
	':plot:': 'http://cbc.pokecommunity.com:8000/assets/plot.gif',
	':pogchamp:': 'http://cbc.pokecommunity.com:8000/assets/pogchamp.png',
	':pole:': 'http://cbc.pokecommunity.com:8000/assets/pole.png',
	':pose:': 'http://cbc.pokecommunity.com:8000/assets/pose.gif',
	':potato:': 'http://cbc.pokecommunity.com:8000/assets/potato.png',
	':primeape:': 'http://cbc.pokecommunity.com:8000/assets/primeape.png',
	':psyduck:': 'http://cbc.pokecommunity.com:8000/assets/psyduck.png',
	':pyoshi:': 'http://cbc.pokecommunity.com:8000/assets/pyoshi.png',
	':raffey:': 'http://cbc.pokecommunity.com:8000/assets/raffey.png',
	':raichu:': 'http://cbc.pokecommunity.com:8000/assets/raichu.png',
	':rainbow:': 'http://cbc.pokecommunity.com:8000/assets/rainbow.gif',
	':ralts:': 'http://cbc.pokecommunity.com:8000/assets/ralts.png',
	':reaper:': 'http://cbc.pokecommunity.com:8000/assets/reaper.png',
	':reinhardt:': 'http://cbc.pokecommunity.com:8000/assets/reinhardt.png',
	':respek:': 'http://cbc.pokecommunity.com:8000/assets/respek.png',
	':roadhog:': 'http://cbc.pokecommunity.com:8000/assets/roadhog.png',
	':roll:': 'http://cbc.pokecommunity.com:8000/assets/roll.gif',
	':roselia:': 'http://cbc.pokecommunity.com:8000/assets/roselia.png',
	':rude:': 'http://cbc.pokecommunity.com:8000/assets/rude.gif',
	':sableye:': 'http://cbc.pokecommunity.com:8000/assets/sableye.png',
	':salute:': 'http://cbc.pokecommunity.com:8000/assets/salute.png',
	':scarfhug:': 'http://cbc.pokecommunity.com:8000/assets/scarfhug.png',
	':scizor:': 'http://cbc.pokecommunity.com:8000/assets/scizor.png',
	':seduce:': 'http://cbc.pokecommunity.com:8000/assets/seduce.png',
	':senpai:': 'http://cbc.pokecommunity.com:8000/assets/senpai.png',
	':sharpie:': 'http://cbc.pokecommunity.com:8000/assets/sharpie.png',
	':shift:': 'http://cbc.pokecommunity.com:8000/assets/shift.gif',
	':shifty:': 'http://cbc.pokecommunity.com:8000/assets/shifty.png',
	':shinx:': 'http://cbc.pokecommunity.com:8000/assets/shinx.png',
	':shinyhug:': 'http://cbc.pokecommunity.com:8000/assets/shinyhug.png',
	':sims:': 'http://cbc.pokecommunity.com:8000/assets/sims.png',
	':skarmory:': 'http://cbc.pokecommunity.com:8000/assets/skarmory.png',
	':slowbro:': 'http://cbc.pokecommunity.com:8000/assets/slowbro.png',
	':slowking:': 'http://cbc.pokecommunity.com:8000/assets/slowking.png',
	':slowpoke:': 'http://cbc.pokecommunity.com:8000/assets/slowpoke.png',
	':snivy:': 'http://cbc.pokecommunity.com:8000/assets/snivy.png',
	':snorlax:': 'http://cbc.pokecommunity.com:8000/assets/snorlax.png',
	':soldier76:': 'http://cbc.pokecommunity.com:8000/assets/soldier76.png',
	':sombra:': 'http://cbc.pokecommunity.com:8000/assets/sombra.png',
	':spasm:': 'http://cbc.pokecommunity.com:8000/assets/spasm.gif',
	':spheal:': 'http://cbc.pokecommunity.com:8000/assets/spheal.png',
	':spinda:': 'http://cbc.pokecommunity.com:8000/assets/spinda.png',
	':squint:': 'http://cbc.pokecommunity.com:8000/assets/squint.png',
	':squirtle:': 'http://cbc.pokecommunity.com:8000/assets/squirtle.png',
	':steelix:': 'http://cbc.pokecommunity.com:8000/assets/steelix.png',
	':stephenking:': 'http://cbc.pokecommunity.com:8000/assets/stephenking.png',
	':strut:': 'http://cbc.pokecommunity.com:8000/assets/strut.png',
	':suicune:': 'http://cbc.pokecommunity.com:8000/assets/suicune.png',
	':superman:': 'http://cbc.pokecommunity.com:8000/assets/superman.png',
	':sweep:': 'http://cbc.pokecommunity.com:8000/assets/sweep.gif',
	':swiftrage:': 'http://cbc.pokecommunity.com:8000/assets/swiftrage.png',
	':symmetra:': 'http://cbc.pokecommunity.com:8000/assets/symmetra.png',
	':taco:': 'http://cbc.pokecommunity.com:8000/assets/taco.png',
	':taillow:': 'http://cbc.pokecommunity.com:8000/assets/taillow.png',
	':thinkeng:': 'http://cbc.pokecommunity.com:8000/assets/thinkeng.png',
	':thonkeng:': 'http://cbc.pokecommunity.com:8000/assets/thinkeng.png',
	':thinkform:': 'http://cbc.pokecommunity.com:8000/assets/thinkform.png',
	':thonk:': 'http://cbc.pokecommunity.com:8000/assets/thonk.png',
	':thonkang:': 'http://cbc.pokecommunity.com:8000/assets/thonkang.png',
	':thugga:': 'http://cbc.pokecommunity.com:8000/assets/thugga.png',
	':torbjorn:': 'http://cbc.pokecommunity.com:8000/assets/torbjorn.png',
	':toxic:': 'http://cbc.pokecommunity.com:8000/assets/toxic.png',
	':tracer:': 'http://cbc.pokecommunity.com:8000/assets/tracer.png',
	':tyranitar:': 'http://cbc.pokecommunity.com:8000/assets/tyranitar.png',
	':ugh:': 'http://cbc.pokecommunity.com:8000/assets/ugh.gif',
	':uhhuh:': 'http://cbc.pokecommunity.com:8000/assets/uhhuh.png',
	':venusaur:': 'http://cbc.pokecommunity.com:8000/assets/venusaur.png',
	':victini:': 'http://cbc.pokecommunity.com:8000/assets/victini.gif',
	':viper:': 'http://cbc.pokecommunity.com:8000/assets/viper.png',
	':voltypride:': 'http://cbc.pokecommunity.com:8000/assets/voltypride.png',
	':vulpix:': 'http://cbc.pokecommunity.com:8000/assets/vulpix.png',
	':wailmer:': 'http://cbc.pokecommunity.com:8000/assets/wailmer.png',
	':wave:': 'http://cbc.pokecommunity.com:8000/assets/wave.gif',
	':weedle:': 'http://cbc.pokecommunity.com:8000/assets/weedle.png',
	':what:': 'http://cbc.pokecommunity.com:8000/assets/what.png',
	':why:': 'http://cbc.pokecommunity.com:8000/assets/why.png',
	':widowmaker:': 'http://cbc.pokecommunity.com:8000/assets/widowmaker.png',
	':wigglytuff:': 'http://cbc.pokecommunity.com:8000/assets/wigglytuff.png',
	':wink:': 'http://cbc.pokecommunity.com:8000/assets/wink.png',
	':winston:': 'http://cbc.pokecommunity.com:8000/assets/winston.png',
	':wlink:': 'http://cbc.pokecommunity.com:8000/assets/wlink.gif',
	':wobbuffet:': 'http://cbc.pokecommunity.com:8000/assets/wobbuffet.png',
	':wooper:': 'http://cbc.pokecommunity.com:8000/assets/wooper.png',
	':wutface:': 'http://cbc.pokecommunity.com:8000/assets/wutface.png',
	':wynaut:': 'http://cbc.pokecommunity.com:8000/assets/wynaut.png',
	':y:': 'http://cbc.pokecommunity.com:8000/assets/y.png',
	':yoshi:': 'http://cbc.pokecommunity.com:8000/assets/yoshi.png',
	':zarya:': 'http://cbc.pokecommunity.com:8000/assets/zarya.png',
	':zenyatta:': 'http://cbc.pokecommunity.com:8000/assets/zenyatta.png',
	':zzz:': 'http://cbc.pokecommunity.com:8000/assets/zzz.gif',
};

function create_table() {
	const emotes_name = Object.keys(emotes);
	const emotes_list = [];
	const emotes_group_list = [];
	const len = emotes_name.length;

	for (let i = 0; i < len; i++) {
		emotes_list.push("<td style='padding: 5px; box-shadow: 0px 0px 2px rgba(0, 0, 0, 0.5) inset; border-radius: 5px;'>" + "<img src='" + emotes[emotes_name[i]] + "'' title='" + emotes_name[i] + "' height='50' width='50' style='vertical-align: middle;  padding-right: 5px;' />" + emotes_name[i] + "</td>");
	}

	for (let i = 0; i < len; i += 4) {
		const emoteOutput = [emotes_list[i], emotes_list[i + 1], emotes_list[i + 2], emotes_list[i + 3]];
		if (i < len) emotes_group_list.push("<tr>" + emoteOutput.join('') + "</tr>");
	}

	return (
		"<div class='infobox'><center><font style='font-weight: bold; text-decoration: underline; color: #555;'>List of Emoticons</font></center>" +
		"<div style='max-height: 300px; overflow-y: scroll; padding: 5px 0px;'><table style='background: rgba(245, 245, 245, 0.4); border: 1px solid #BBB;' width='100%'>" +
		emotes_group_list.join("") +
		"</table></div></div>"
	);
}

const emotes_table = create_table();

exports.commands = {
	blockemote: 'blockemoticons',
	blockemotes: 'blockemoticons',
	blockemoticon: 'blockemoticons',
	blockemoticons(target, room, user) {
		if (user.blockEmoticons === (target || true)) return this.sendReply("You are already blocking emoticons in private messages! To unblock, use /unblockemoticons");
		user.blockEmoticons = true;
		return this.sendReply("You are now blocking emoticons in private messages.");
	},
	blockemoticonshelp: ["/blockemoticons - Blocks emoticons in private messages. Unblock them with /unblockemoticons."],

	unblockemote: 'unblockemoticons',
	unblockemotes: 'unblockemoticons',
	unblockemoticon: 'unblockemoticons',
	unblockemoticons(target, room, user) {
		if (!user.blockEmoticons) return this.sendReply("You are not blocking emoticons in private messages! To block, use /blockemoticons");
		user.blockEmoticons = false;
		return this.sendReply("You are no longer blocking emoticons in private messages.");
	},
	unblockemoticonshelp: ["/unblockemoticons - Unblocks emoticons in private messages. Block them with /blockemoticons."],

	emotes: 'emoticons',
	emoticons(target, room, user) {
		if (!this.runBroadcast()) return;
		this.sendReply("|raw|" + emotes_table);
	},
	emoticonshelp: ["/emoticons - Get a list of emoticons."],

	toggleemote: 'toggleemoticons',
	toggleemotes: 'toggleemoticons',
	toggleemoticons(target, room, user) {
		if (!this.can('declare', null, room)) return false;
		room.disableEmoticons = !room.disableEmoticons;
		this.sendReply("Disallowing emoticons is set to " + room.disableEmoticons + " in this room.");
		if (room.disableEmoticons) {
			this.add("|raw|<div class=\"broadcast-red\"><b>Emoticons are disabled!</b><br />Emoticons will not work.</div>");
		} else {
			this.add("|raw|<div class=\"broadcast-blue\"><b>Emoticons are enabled!</b><br />Emoticons will work now.</div>");
		}
	},
	toggleemoticonshelp: ["/toggleemoticons - Toggle emoticons on or off."],
};
