'use strict';

/**
* Create a two column table listing emoticons.
*
* @return {String} emotes table
*/
const emotes = {
	':4head:': 'http://cbc.pokecommunity.com/server/config/emoticons/4head.png',
	':absol:': 'http://cbc.pokecommunity.com/server/config/emoticons/absol.png',
	':aggron:': 'http://cbc.pokecommunity.com/server/config/emoticons/aggron.png',
	':aids:': 'http://cbc.pokecommunity.com/server/config/emoticons/aids.png',
	':alarm:': 'http://cbc.pokecommunity.com/server/config/emoticons/alarm.gif',
	':ampharos:': 'http://cbc.pokecommunity.com/server/config/emoticons/ampharos.png',
	':ana:': 'http://cbc.pokecommunity.com/server/config/emoticons/ana.png',
	':arcanine:': 'http://cbc.pokecommunity.com/server/config/emoticons/arcanine.png',
	':arceus:': 'http://cbc.pokecommunity.com/server/config/emoticons/arceus.png',
	':armycat:': 'http://cbc.pokecommunity.com/server/config/emoticons/armycat.png',
	':ashhug:': 'http://cbc.pokecommunity.com/server/config/emoticons/ashhug.png',
	':ball:': 'http://cbc.pokecommunity.com/server/config/emoticons/ball.gif',
	':barrel:': 'http://cbc.pokecommunity.com/server/config/emoticons/barrel.gif',
	':bastion:': 'http://cbc.pokecommunity.com/server/config/emoticons/bastion.png',
	':bearhug:': 'http://cbc.pokecommunity.com/server/config/emoticons/bearhug.png',
	':bed:': 'http://cbc.pokecommunity.com/server/config/emoticons/bed.gif',
	':bellossom:': 'http://cbc.pokecommunity.com/server/config/emoticons/bellossom.png',
	':bidoof:': 'http://cbc.pokecommunity.com/server/config/emoticons/bidoof.png',
	':blastoise:': 'http://cbc.pokecommunity.com/server/config/emoticons/blastoise.png',
	':blink:': 'http://cbc.pokecommunity.com/server/config/emoticons/blink.gif',
	':blissey:': 'http://cbc.pokecommunity.com/server/config/emoticons/blissey.png',
	':blush:': 'http://cbc.pokecommunity.com/server/config/emoticons/blush.png',
	':blust:': 'http://cbc.pokecommunity.com/server/config/emoticons/blust.gif',
	':boatydrugs:': 'http://cbc.pokecommunity.com/server/config/emoticons/boatydrugs.png',
	':bowie:': 'http://cbc.pokecommunity.com/server/config/emoticons/bowie.png',
	':bulbasaur:': 'http://cbc.pokecommunity.com/server/config/emoticons/bulbasaur.png',
	':bunny:': 'http://cbc.pokecommunity.com/server/config/emoticons/bunny.gif',
	':camiss:': 'http://cbc.pokecommunity.com/server/config/emoticons/camiss.png',
	':carol:': 'http://cbc.pokecommunity.com/server/config/emoticons/carol.png',
	':castform:': 'http://cbc.pokecommunity.com/server/config/emoticons/castform.png',
	':catflip:': 'http://cbc.pokecommunity.com/server/config/emoticons/catflip.png',
	':censor:': 'http://cbc.pokecommunity.com/server/config/emoticons/censor.png',
	':chansey:': 'http://cbc.pokecommunity.com/server/config/emoticons/chansey.png',
	':charizard:': 'http://cbc.pokecommunity.com/server/config/emoticons/charizard.png',
	':charmander:': 'http://cbc.pokecommunity.com/server/config/emoticons/charmander.png',
	':cheers:': 'http://cbc.pokecommunity.com/server/config/emoticons/cheers.png',
	':chikorita:': 'http://cbc.pokecommunity.com/server/config/emoticons/chikorita.png',
	':choicehug:': 'http://cbc.pokecommunity.com/server/config/emoticons/choicehug.png',
	':choke:': 'http://cbc.pokecommunity.com/server/config/emoticons/choke.png',
	':christos:': 'http://cbc.pokecommunity.com/server/config/emoticons/christos.png',
	':clefairy:': 'http://cbc.pokecommunity.com/server/config/emoticons/clefairy.png',
	':clown:': 'http://cbc.pokecommunity.com/server/config/emoticons/clown.png',
	':cookie:': 'http://cbc.pokecommunity.com/server/config/emoticons/cookie.png',
	':cthulhu:': 'http://cbc.pokecommunity.com/server/config/emoticons/cthulhu.png',
	':curry:': 'http://cbc.pokecommunity.com/server/config/emoticons/curry.png',
	':dab:': 'http://cbc.pokecommunity.com/server/config/emoticons/dab.png',
	':dance:': 'http://cbc.pokecommunity.com/server/config/emoticons/dance.gif',
	':dedenne:': 'http://cbc.pokecommunity.com/server/config/emoticons/dedenne.png',
	':delivert:': 'http://cbc.pokecommunity.com/server/config/emoticons/delivert.png',
	':diddy:': 'http://cbc.pokecommunity.com/server/config/emoticons/diddy.png',
	':dinner:': 'http://cbc.pokecommunity.com/server/config/emoticons/dinner.png',
	':ditto:': 'http://cbc.pokecommunity.com/server/config/emoticons/ditto.png',
	':dk:': 'http://cbc.pokecommunity.com/server/config/emoticons/dk.png',
	':doomfist:': 'http://cbc.pokecommunity.com/server/config/emoticons/doomfist.png',
	':drama:': 'http://cbc.pokecommunity.com/server/config/emoticons/drama.png',
	':drowzee:': 'http://cbc.pokecommunity.com/server/config/emoticons/drowzee.png',
	':dva:': 'http://cbc.pokecommunity.com/server/config/emoticons/dva.png',
	':eevee:': 'http://cbc.pokecommunity.com/server/config/emoticons/eevee.png',
	':electrode:': 'http://cbc.pokecommunity.com/server/config/emoticons/electrode.png',
	':emboar:': 'http://cbc.pokecommunity.com/server/config/emoticons/emboar.png',
	':espurr:': 'http://cbc.pokecommunity.com/server/config/emoticons/espurr.png',
	':eyes:': 'http://cbc.pokecommunity.com/server/config/emoticons/eyes.png',
	':fatbowie:': 'http://cbc.pokecommunity.com/server/config/emoticons/bowie.png',
	':feebas:': 'http://cbc.pokecommunity.com/server/config/emoticons/feebas.png',
	':fish:': 'http://cbc.pokecommunity.com/server/config/emoticons/fish.gif',
	':flirt:': 'http://cbc.pokecommunity.com/server/config/emoticons/flirt.png',
	':flygon:': 'http://cbc.pokecommunity.com/server/config/emoticons/flygon.png',
	':frank:': 'http://cbc.pokecommunity.com/server/config/emoticons/frank.png',
	':gav:': 'http://cbc.pokecommunity.com/server/config/emoticons/gav.png',
	':gawk:': 'http://cbc.pokecommunity.com/server/config/emoticons/gawk.png',
	':genji:': 'http://cbc.pokecommunity.com/server/config/emoticons/genji.png',
	':glare:': 'http://cbc.pokecommunity.com/server/config/emoticons/glare.png',
	':gloom:': 'http://cbc.pokecommunity.com/server/config/emoticons/gloom.png',
	':goodra:': 'http://cbc.pokecommunity.com/server/config/emoticons/goodra.png',
	':goomy:': 'http://cbc.pokecommunity.com/server/config/emoticons/goomy.png',
	':growlithe:': 'http://cbc.pokecommunity.com/server/config/emoticons/growlithe.png',
	':hamster:': 'http://cbc.pokecommunity.com/server/config/emoticons/hamster.png',
	':hamtaro:': 'http://cbc.pokecommunity.com/server/config/emoticons/hamtaro.gif',
	':hanzo:': 'http://cbc.pokecommunity.com/server/config/emoticons/hanzo.png',
	':harambe:': 'http://cbc.pokecommunity.com/server/config/emoticons/harambe.png',
	':helix:': 'http://cbc.pokecommunity.com/server/config/emoticons/helix.png',
	':houndoom:': 'http://cbc.pokecommunity.com/server/config/emoticons/houndoom.png',
	':hug:': 'http://cbc.pokecommunity.com/server/config/emoticons/hug.png',
	':hypno:': 'http://cbc.pokecommunity.com/server/config/emoticons/hypno.png',
	':infernape:': 'http://cbc.pokecommunity.com/server/config/emoticons/infernape.png',
	':jack:': 'http://cbc.pokecommunity.com/server/config/emoticons/jack.png',
	':jigglypuff:': 'http://cbc.pokecommunity.com/server/config/emoticons/jigglypuff.png',
	':joanne:': 'http://cbc.pokecommunity.com/server/config/emoticons/joanne.png',
	':junkrat:': 'http://cbc.pokecommunity.com/server/config/emoticons/junkrat.png',
	':jynx:': 'http://cbc.pokecommunity.com/server/config/emoticons/jynx.png',
	':kanye:': 'http://cbc.pokecommunity.com/server/config/emoticons/kanye.png',
	':kappa:': 'http://cbc.pokecommunity.com/server/config/emoticons/kappa.png',
	':kappapride:': 'http://cbc.pokecommunity.com/server/config/emoticons/kappapride.png',
	':kappaross:': 'http://cbc.pokecommunity.com/server/config/emoticons/kappaross.png',
	':keepo:': 'http://cbc.pokecommunity.com/server/config/emoticons/keepo.png',
	':kermit:': 'http://cbc.pokecommunity.com/server/config/emoticons/kermit.png',
	':khaled:': 'http://cbc.pokecommunity.com/server/config/emoticons/khaled.png',
	':kitty:': 'http://cbc.pokecommunity.com/server/config/emoticons/kitty.png',
	':kreygasm:': 'http://cbc.pokecommunity.com/server/config/emoticons/kreygasm.png',
	':lapras:': 'http://cbc.pokecommunity.com/server/config/emoticons/lapras.png',
	':latias:': 'http://cbc.pokecommunity.com/server/config/emoticons/latias.png',
	':latios:': 'http://cbc.pokecommunity.com/server/config/emoticons/latios.png',
	':ledian:': 'http://cbc.pokecommunity.com/server/config/emoticons/ledian.png',
	':leg:': 'http://cbc.pokecommunity.com/server/config/emoticons/leg.png',
	':lewd:': 'http://cbc.pokecommunity.com/server/config/emoticons/lewd.png',
	':lickilicky:': 'http://cbc.pokecommunity.com/server/config/emoticons/lickilicky.png',
	':lickitung:': 'http://cbc.pokecommunity.com/server/config/emoticons/lickitung.gif',
	':lileep:': 'http://cbc.pokecommunity.com/server/config/emoticons/lileep.png',
	':link:': 'http://cbc.pokecommunity.com/server/config/emoticons/link.png',
	':loudred:': 'http://cbc.pokecommunity.com/server/config/emoticons/loudred.png',
	':lucio:': 'http://cbc.pokecommunity.com/server/config/emoticons/lucio.png',
	':ludicolo:': 'http://cbc.pokecommunity.com/server/config/emoticons/ludicolo.png',
	':luvdisc:': 'http://cbc.pokecommunity.com/server/config/emoticons/luvdisc.png',
	':lyin:': 'http://cbc.pokecommunity.com/server/config/emoticons/lyin.png',
	':magikarp:': 'http://cbc.pokecommunity.com/server/config/emoticons/magikarp.png',
	':mccree:': 'http://cbc.pokecommunity.com/server/config/emoticons/mccree.png',
	':meganium:': 'http://cbc.pokecommunity.com/server/config/emoticons/meganium.png',
	':mei:': 'http://cbc.pokecommunity.com/server/config/emoticons/mei.png',
	':meowstic:': 'http://cbc.pokecommunity.com/server/config/emoticons/meowstic.png',
	':meowsticf:': 'http://cbc.pokecommunity.com/server/config/emoticons/meowsticf.png',
	':meowth:': 'http://cbc.pokecommunity.com/server/config/emoticons/meowth.png',
	':mercy:': 'http://cbc.pokecommunity.com/server/config/emoticons/mercy.png',
	':mermaid:': 'http://cbc.pokecommunity.com/server/config/emoticons/mermaid.png',
	':metagross:': 'http://cbc.pokecommunity.com/server/config/emoticons/metagross.png',
	':mind:': 'http://cbc.pokecommunity.com/server/config/emoticons/mind.png',
	':moo:': 'http://cbc.pokecommunity.com/server/config/emoticons/moo.gif',
	':mrmime:': 'http://cbc.pokecommunity.com/server/config/emoticons/mrmime.png',
	':mudkip:': 'http://cbc.pokecommunity.com/server/config/emoticons/mudkip.png',
	':muk:': 'http://cbc.pokecommunity.com/server/config/emoticons/muk.png',
	':no:': 'http://cbc.pokecommunity.com/server/config/emoticons/no.png',
	':nw:': 'http://cbc.pokecommunity.com/server/config/emoticons/nw.gif',
	':oddish:': 'http://cbc.pokecommunity.com/server/config/emoticons/oddish.png',
	':ok:': 'http://cbc.pokecommunity.com/server/config/emoticons/ok.png',
	':orisa:': 'http://cbc.pokecommunity.com/server/config/emoticons/orisa.png',
	':pachirisu:': 'http://cbc.pokecommunity.com/server/config/emoticons/pachirisu.png',
	':pancham:': 'http://cbc.pokecommunity.com/server/config/emoticons/pancham.png',
	':pangoro:': 'http://cbc.pokecommunity.com/server/config/emoticons/pangoro.png',
	':papabless:': 'http://cbc.pokecommunity.com/server/config/emoticons/papabless.png',
	':papi:': 'http://cbc.pokecommunity.com/server/config/emoticons/papi.png',
	':pear:': 'http://cbc.pokecommunity.com/server/config/emoticons/pear.png',
	':petty:': 'http://cbc.pokecommunity.com/server/config/emoticons/petty.png',
	':pharah:': 'http://cbc.pokecommunity.com/server/config/emoticons/pharah.png',
	':pikachu:': 'http://cbc.pokecommunity.com/server/config/emoticons/pikachu.png',
	':pikahug:': 'http://cbc.pokecommunity.com/server/config/emoticons/pikahug.png',
	':pix:': 'http://cbc.pokecommunity.com/server/config/emoticons/pix.png',
	':pjsalt:': 'http://cbc.pokecommunity.com/server/config/emoticons/pjsalt.png',
	':plot:': 'http://cbc.pokecommunity.com/server/config/emoticons/plot.gif',
	':pogchamp:': 'http://cbc.pokecommunity.com/server/config/emoticons/pogchamp.png',
	':pole:': 'http://cbc.pokecommunity.com/server/config/emoticons/pole.png',
	':pose:': 'http://cbc.pokecommunity.com/server/config/emoticons/pose.gif',
	':potato:': 'http://cbc.pokecommunity.com/server/config/emoticons/potato.png',
	':primeape:': 'http://cbc.pokecommunity.com/server/config/emoticons/primeape.png',
	':psyduck:': 'http://cbc.pokecommunity.com/server/config/emoticons/psyduck.png',
	':pyoshi:': 'http://cbc.pokecommunity.com/server/config/emoticons/pyoshi.png',
	':raffey:': 'http://cbc.pokecommunity.com/server/config/emoticons/raffey.png',
	':raichu:': 'http://cbc.pokecommunity.com/server/config/emoticons/raichu.png',
	':rainbow:': 'http://cbc.pokecommunity.com/server/config/emoticons/rainbow.gif',
	':ralts:': 'http://cbc.pokecommunity.com/server/config/emoticons/ralts.png',
	':reaper:': 'http://cbc.pokecommunity.com/server/config/emoticons/reaper.png',
	':reinhardt:': 'http://cbc.pokecommunity.com/server/config/emoticons/reinhardt.png',
	':respek:': 'http://cbc.pokecommunity.com/server/config/emoticons/respek.png',
	':roadhog:': 'http://cbc.pokecommunity.com/server/config/emoticons/roadhog.png',
	':roll:': 'http://cbc.pokecommunity.com/server/config/emoticons/roll.gif',
	':roselia:': 'http://cbc.pokecommunity.com/server/config/emoticons/roselia.png',
	':rude:': 'http://cbc.pokecommunity.com/server/config/emoticons/rude.gif',
	':sableye:': 'http://cbc.pokecommunity.com/server/config/emoticons/sableye.png',
	':salute:': 'http://cbc.pokecommunity.com/server/config/emoticons/salute.png',
	':scarfhug:': 'http://cbc.pokecommunity.com/server/config/emoticons/scarfhug.png',
	':scizor:': 'http://cbc.pokecommunity.com/server/config/emoticons/scizor.png',
	':seduce:': 'http://cbc.pokecommunity.com/server/config/emoticons/seduce.png',
	':senpai:': 'http://cbc.pokecommunity.com/server/config/emoticons/senpai.png',
	':sharpie:': 'http://cbc.pokecommunity.com/server/config/emoticons/sharpie.png',
	':shift:': 'http://cbc.pokecommunity.com/server/config/emoticons/shift.gif',
	':shifty:': 'http://cbc.pokecommunity.com/server/config/emoticons/shifty.png',
	':shinx:': 'http://cbc.pokecommunity.com/server/config/emoticons/shinx.png',
	':shinyhug:': 'http://cbc.pokecommunity.com/server/config/emoticons/shinyhug.png',
	':sims:': 'http://cbc.pokecommunity.com/server/config/emoticons/sims.png',
	':skarmory:': 'http://cbc.pokecommunity.com/server/config/emoticons/skarmory.png',
	':slowbro:': 'http://cbc.pokecommunity.com/server/config/emoticons/slowbro.png',
	':slowking:': 'http://cbc.pokecommunity.com/server/config/emoticons/slowking.png',
	':slowpoke:': 'http://cbc.pokecommunity.com/server/config/emoticons/slowpoke.png',
	':snivy:': 'http://cbc.pokecommunity.com/server/config/emoticons/snivy.png',
	':snorlax:': 'http://cbc.pokecommunity.com/server/config/emoticons/snorlax.png',
	':soldier76:': 'http://cbc.pokecommunity.com/server/config/emoticons/soldier76.png',
	':sombra:': 'http://cbc.pokecommunity.com/server/config/emoticons/sombra.png',
	':spasm:': 'http://cbc.pokecommunity.com/server/config/emoticons/spasm.gif',
	':spheal:': 'http://cbc.pokecommunity.com/server/config/emoticons/spheal.png',
	':spinda:': 'http://cbc.pokecommunity.com/server/config/emoticons/spinda.png',
	':squint:': 'http://cbc.pokecommunity.com/server/config/emoticons/squint.png',
	':squirtle:': 'http://cbc.pokecommunity.com/server/config/emoticons/squirtle.png',
	':steelix:': 'http://cbc.pokecommunity.com/server/config/emoticons/steelix.png',
	':stephenking:': 'http://cbc.pokecommunity.com/server/config/emoticons/stephenking.png',
	':strut:': 'http://cbc.pokecommunity.com/server/config/emoticons/strut.png',
	':suicune:': 'http://cbc.pokecommunity.com/server/config/emoticons/suicune.png',
	':superman:': 'http://cbc.pokecommunity.com/server/config/emoticons/superman.png',
	':sweep:': 'http://cbc.pokecommunity.com/server/config/emoticons/sweep.gif',
	':swiftrage:': 'http://cbc.pokecommunity.com/server/config/emoticons/swiftrage.png',
	':symmetra:': 'http://cbc.pokecommunity.com/server/config/emoticons/symmetra.png',
	':taco:': 'http://cbc.pokecommunity.com/server/config/emoticons/taco.png',
	':taillow:': 'http://cbc.pokecommunity.com/server/config/emoticons/taillow.png',
	':thinkeng:': 'http://cbc.pokecommunity.com/server/config/emoticons/thinkeng.png',
	':thonkeng:': 'http://cbc.pokecommunity.com/server/config/emoticons/thinkeng.png',
	':thinkform:': 'http://cbc.pokecommunity.com/server/config/emoticons/thinkform.png',
	':thonk:': 'http://cbc.pokecommunity.com/server/config/emoticons/thonk.png',
	':thonkang:': 'http://cbc.pokecommunity.com/server/config/emoticons/thonkang.png',
	':thugga:': 'http://cbc.pokecommunity.com/server/config/emoticons/thugga.png',
	':torbjorn:': 'http://cbc.pokecommunity.com/server/config/emoticons/torbjorn.png',
	':toxic:': 'http://cbc.pokecommunity.com/server/config/emoticons/toxic.png',
	':tracer:': 'http://cbc.pokecommunity.com/server/config/emoticons/tracer.png',
	':tyranitar:': 'http://cbc.pokecommunity.com/server/config/emoticons/tyranitar.png',
	':ugh:': 'http://cbc.pokecommunity.com/server/config/emoticons/ugh.gif',
	':uhhuh:': 'http://cbc.pokecommunity.com/server/config/emoticons/uhhuh.png',
	':venusaur:': 'http://cbc.pokecommunity.com/server/config/emoticons/venusaur.png',
	':victini:': 'http://cbc.pokecommunity.com/server/config/emoticons/victini.gif',
	':viper:': 'http://cbc.pokecommunity.com/server/config/emoticons/viper.png',
	':voltypride:': 'http://cbc.pokecommunity.com/server/config/emoticons/voltypride.png',
	':vulpix:': 'http://cbc.pokecommunity.com/server/config/emoticons/vulpix.png',
	':wailmer:': 'http://cbc.pokecommunity.com/server/config/emoticons/wailmer.png',
	':wave:': 'http://cbc.pokecommunity.com/server/config/emoticons/wave.gif',
	':weedle:': 'http://cbc.pokecommunity.com/server/config/emoticons/weedle.png',
	':what:': 'http://cbc.pokecommunity.com/server/config/emoticons/what.png',
	':why:': 'http://cbc.pokecommunity.com/server/config/emoticons/why.png',
	':widowmaker:': 'http://cbc.pokecommunity.com/server/config/emoticons/widowmaker.png',
	':wigglytuff:': 'http://cbc.pokecommunity.com/server/config/emoticons/wigglytuff.png',
	':wink:': 'http://cbc.pokecommunity.com/server/config/emoticons/wink.png',
	':winston:': 'http://cbc.pokecommunity.com/server/config/emoticons/winston.png',
	':wlink:': 'http://cbc.pokecommunity.com/server/config/emoticons/wlink.gif',
	':wobbuffet:': 'http://cbc.pokecommunity.com/server/config/emoticons/wobbuffet.png',
	':wooper:': 'http://cbc.pokecommunity.com/server/config/emoticons/wooper.png',
	':wutface:': 'http://cbc.pokecommunity.com/server/config/emoticons/wutface.png',
	':wynaut:': 'http://cbc.pokecommunity.com/server/config/emoticons/wynaut.png',
	':y:': 'http://cbc.pokecommunity.com/server/config/emoticons/y.png',
	':yoshi:': 'http://cbc.pokecommunity.com/server/config/emoticons/yoshi.png',
	':zarya:': 'http://cbc.pokecommunity.com/server/config/emoticons/zarya.png',
	':zenyatta:': 'http://cbc.pokecommunity.com/server/config/emoticons/zenyatta.png',
	':zzz:': 'http://cbc.pokecommunity.com/server/config/emoticons/zzz.gif',
};

function create_table() {
	const emotes_name = Object.keys(emotes);
	const emotes_list = [];
	const emotes_group_list = [];
	const len = emotes_name.length;

	for (let i = 0; i < len; i++) {
		emotes_list.push("<td style='padding: 5px; box-shadow: 0px 0px 2px rgba(0, 0, 0, 0.5) inset; border-radius: 5px;'>" + "<img src='" + emotes[emotes_name[i]] + "'' title='" + emotes_name[i] + "' height='50' width='50' style='vertical-align: middle;  padding-right: 5px;' />" + emotes_name[i] + "</td>");
	}

	for (let i = 0; i < len; i += 4) {
		const emoteOutput = [emotes_list[i], emotes_list[i + 1], emotes_list[i + 2], emotes_list[i + 3]];
		if (i < len) emotes_group_list.push("<tr>" + emoteOutput.join('') + "</tr>");
	}

	return (
		"<div class='infobox'><center><font style='font-weight: bold; text-decoration: underline; color: #555;'>List of Emoticons</font></center>" +
		"<div style='max-height: 300px; overflow-y: scroll; padding: 5px 0px;'><table style='background: rgba(245, 245, 245, 0.4); border: 1px solid #BBB;' width='100%'>" +
		emotes_group_list.join("") +
		"</table></div></div>"
	);
}

const emotes_table = create_table();

exports.commands = {
	blockemote: 'blockemoticons',
	blockemotes: 'blockemoticons',
	blockemoticon: 'blockemoticons',
	blockemoticons(target, room, user) {
		if (user.blockEmoticons === (target || true)) return this.sendReply("You are already blocking emoticons in private messages! To unblock, use /unblockemoticons");
		user.blockEmoticons = true;
		return this.sendReply("You are now blocking emoticons in private messages.");
	},
	blockemoticonshelp: ["/blockemoticons - Blocks emoticons in private messages. Unblock them with /unblockemoticons."],

	unblockemote: 'unblockemoticons',
	unblockemotes: 'unblockemoticons',
	unblockemoticon: 'unblockemoticons',
	unblockemoticons(target, room, user) {
		if (!user.blockEmoticons) return this.sendReply("You are not blocking emoticons in private messages! To block, use /blockemoticons");
		user.blockEmoticons = false;
		return this.sendReply("You are no longer blocking emoticons in private messages.");
	},
	unblockemoticonshelp: ["/unblockemoticons - Unblocks emoticons in private messages. Block them with /blockemoticons."],

	emotes: 'emoticons',
	emoticons(target, room, user) {
		if (!this.runBroadcast()) return;
		this.sendReply("|raw|" + emotes_table);
	},
	emoticonshelp: ["/emoticons - Get a list of emoticons."],

	toggleemote: 'toggleemoticons',
	toggleemotes: 'toggleemoticons',
	toggleemoticons(target, room, user) {
		if (!this.can('declare', null, room)) return false;
		room.disableEmoticons = !room.disableEmoticons;
		this.sendReply("Disallowing emoticons is set to " + room.disableEmoticons + " in this room.");
		if (room.disableEmoticons) {
			this.add("|raw|<div class=\"broadcast-red\"><b>Emoticons are disabled!</b><br />Emoticons will not work.</div>");
		} else {
			this.add("|raw|<div class=\"broadcast-blue\"><b>Emoticons are enabled!</b><br />Emoticons will work now.</div>");
		}
	},
	toggleemoticonshelp: ["/toggleemoticons - Toggle emoticons on or off."],
};
